apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node
  replicas: 2 #number of pods to create 
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: ajay946/hello-world:v1
        ports:
        - containerPort: 8081

